eureka:
  instance:
    hostname: {EUREKA_INSTANCE_HOSTNAME}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: {EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}

spring:
  data:
    redis:
      url: {REDIS_URL}
  kafka:
    bootstrap-servers: {KAFKA_BOOTSTRAP_SERVERS}

keycloak:
  auth-server-url: {KEYCLOAK_AUTH_SERVER_URL}
  realm: {KEYCLOAK_REALM}
  credentials:
    client-id: {KEYCLOAK_CREDENTIALS_CLIENT_ID}
    secret: {KEYCLOAK_CREDENTIALS_SECRET}
  jwks-certs: {KEYCLOAK_JWKS_CERTS}


