apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: onlineakimbank
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: [ 'prometheus:9090' ]
      - job_name: 'api-gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'api-gateway:9191' ]
      - job_name: 'auth-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'auth-service:8080' ]
      - job_name: 'user-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'user-service:8081' ]
      - job_name: 'account-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'account-service:8082' ]
      - job_name: 'card-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'card-service:8083' ]
      - job_name: 'payment-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'payment-service:8084' ]
      - job_name: 'transaction-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'transaction-service:8085' ]
      - job_name: 'loan-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'loan-service:8086' ]
      - job_name: 'notification-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'notification-service:8087' ]
      - job_name: 'admin-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'admin-service:8088' ]
      - job_name: 'document-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'document-service:8089' ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: onlineakimbank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: onlineakimbank
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
