server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: user-service
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus